export const USER_LOGIN_REQUEST = '@@user/LOGIN/REQUEST';
export const USER_LOGIN_SUCCESS = '@@user/LOGIN/SUCCESS';
export const USER_LOGIN_FAILURE = '@@user/LOGIN/FAILURE';

export const USER_CHECK_LOGIN_REQUEST = '@@user/CHECK_LOGIN/REQUEST';
export const USER_CHECK_LOGIN_SUCCESS = '@@user/CHECK_LOGIN/SUCCESS';
export const USER_CHECK_LOGIN_FAILURE = '@@user/CHECK_LOGIN/FAILURE';

export const USER_LOGOUT_REQUEST = '@@user/CHECK_LOGIN/REQUEST';
export const USER_LOGOUT_SUCCESS = '@@user/CHECK_LOGIN/SUCCESS';
export const USER_LOGOUT_FAILURE = '@@user/CHECK_LOGIN/FAILURE';
